---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: thinkpad
    image: "geerlingguy/docker-debian12-ansible"
    pre_build_image: true
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /var/lib/containerd
    cgroupns_mode: host
    privileged: true
provisioner:
  name: ansible
  config_options:
    defaults:
      display_skipped_hosts: false
      display_ok_hosts: false
verifier:
  name: ansible
